### ISSUE TITLE
Update landscan_pop

### ISSUE THREAD

**Issue by jacobwhall** [aiddata/geo-datasets#137]
- Use Dataset class
- Check for updated data to import

**Comment by sgoodm** [comment]
Full tested and run with data in pre_geo dir, so needs to be moved over to geo before running ingest.

The structure of the downloaded data changed significantly since last time, so I am inclined to make a fresh dir for this rather than just adding to or replacing the existing one. 

Note that the output filenames have changes as well, so if we just moved the old ones elsewhere we still need to update the resource list on ingest (but it shouldn't trigger reprocessing since the resource name - just path - doesn't change)

**Comment by sgoodm** [comment]
ingest completed, confirmed updating resource path does not trigger reprocessing
